version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - JWT_SECRET=eviBMvM62ASRaeVf445aoMLYuK49nVzbv7X7JEhXYuZMvfUwxx3kuKd2H7dnrrfw
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
