version: '3'

services:
  client:
    build:
      context: ./client
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
