name: Delete

on:
  delete:
    branches: ['**']

  workflow_dispatch:

jobs:
  build:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        env:
          BRANCH: ${{ github.event.ref }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BRANCH
          script: |
            cd /var/www

            echo BRANCH $BRANCH

            branch=${BRANCH##*/}

            echo branch $branch

            if [ "$branch" = "master" ]; then
              exit
            fi

            cd git/$branch

            pwd
            ls

            docker-compose down

            cd ..

            pwd
            ls

            rm -rf $branch

            pwd
            ls
