# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ['**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: |
          export BRANCH=${GITHUB_REF##*/}
          echo "::set-env name=BRANCH::$BRANCH"
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        env:
          BRANCH: $BRANCH
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BRANCH
          script: |
            cd /var/www
            ./setupBranch $BRANCH
