# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ['**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        env:
          BRANCH: ${{ github.ref }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BRANCH
          script: |
            cd /var/www
            #./setupBranch ${BRANCH##*/}

            branch=${BRANCH##*/}
            echo $branch

            eval $(ssh-agent)
            ssh-add ~/.ssh/ed25519

            ppref="$branch"
            ppref+="."
            cpref="$branch"
            cpref+="_"

            export PATHPREFIX="$ppref"
            export CONTAINERPREFIX="$cpref"
            echo $PATHPREFIX
            echo $CONTAINERPREFIX

            if [ -d "git/$branch" ]; then
                    echo "going to git/$branch"
                    cd git/$branch
                    docker-compose down
                    git pull
            else
                    git clone -b $branch git@github.com:4IT580/joinme.git git/$branch
                    cd git/$branch
            fi

            cp /var/www/docker-compose.override.yml docker-compose.override.yml

            if [ "$branch" = "master" ]; then
                    export PATHPREFIX=""
                    echo $PATHPREFIX
                    echo "I AM MASTER"       
            fi

            docker-compose -f docker-compose.caddy.yml up -d --build
